import { Suspense } from 'react'
import { Target } from 'lucide-react'
import { api } from '@/api/client'
import { RuleGrid } from './rule-grid'

export default function Rules() {
  const rules = api.getRules()

  const groups = [
    { label: 'Security', rules: rules.filter((r) => r.category === 'Security') },
    { label: 'Quality', rules: rules.filter((r) => r.category === 'Quality') },
    { label: 'Architecture', rules: rules.filter((r) => r.category === 'Architecture') },
  ]

  return (
    <div className="space-y-6 animate-fade-up">
      <div>
        <div className="text-[11px] font-semibold uppercase tracking-wider text-primary">Rule Engine</div>
        <h1 className="mt-1 text-2xl font-bold text-white">Analysis Rule Engine</h1>
        <p className="mt-1 max-w-2xl text-sm text-white/50">
          Every analysis result is generated by deterministic rules. This page lists all active rules, their
          trigger conditions and detection counts.
        </p>
      </div>

      <div className="flex items-center gap-2 text-[11px] text-white/35">
        <Target className="h-3.5 w-3.5" />
        {rules.length} rules active · results are not AI-generated
      </div>

      {/* The grid reads ?rule= to highlight a rule, which is only known in the
          browser, so it renders inside a Suspense boundary. */}
      <Suspense fallback={<div className="h-96 animate-pulse rounded-xl border border-edge bg-shell" />}>
        <RuleGrid groups={groups} />
      </Suspense>
    </div>
  )
}
